export enum FORM_VALIDITY_ACTION_TYPES {
  SET_FORM_VALIDITY_TRUE = 'errors/SET_FORM_VALIDITY_TRUE',
  SET_FORM_VALIDITY_FALSE = 'errors/SET_FORM_VALIDITY_FALSE',
}

export enum ERROR_MESSAGE_ACTION_TYPES {
  SET_ERROR_MESSAGE = 'errors/SET_ERROR_MESSAGE',
  REMOVE_ERROR_MESSAGE = 'errors/REMOVE_ERROR_MESSAGE',
}
