export enum SIGNIN_POPUP_ACTION_TYPES {
  SET_SIGNIN_POPUP_OPEN = 'toggles/SET_SIGNIN_POPUP_OPEN',
  SET_SIGNIN_POPUP_CLOSED = 'toggles/SET_SIGNIN_POPUP_CLOSED',
}

export enum SIGNUP_POPUP_ACTION_TYPES {
  SET_SIGNUP_POPUP_OPEN = 'toggles/SET_SIGNUP_POPUP_OPEN',
  SET_SIGNUP_POPUP_CLOSED = 'toggles/SET_SIGNUP_POPUP_CLOSED',
}

export enum INFO_TOOLTIP_ACTION_TYPES {
  SET_INFO_TOOLTIP_OPEN = 'toggles/SET_INFO_TOOLTIP_OPEN',
  SET_INFO_TOOLTIP_CLOSED = 'toggles/SET_INFO_TOOLTIP_CLOSED',
}

export enum ISLOADING_ACTION_TYPES {
  SET_ISLOADING_TRUE = 'toggles/SET_ISLOADING_TRUE',
  SET_ISLOADING_FALSE = 'toggles/SET_ISLOADING_FALSE',
}

export enum ISLOADING_TEXT_ACTION_TYPES {
  SET_ISLOADING_TEXT_TRUE = 'toggles/SET_ISLOADING_TEXT_TRUE',
  SET_ISLOADING_TEXT_FALSE = 'toggles/SET_ISLOADING_TEXT_FALSE',
}

export enum ISLOGGEDIN_ACTION_TYPES {
  SET_ISLOGGEDIN_TRUE = 'toggles/SET_ISLOGGEDIN_TRUE',
  SET_ISLOGGEDIN_FALSE = 'toggles/SET_ISLOGGEDIN_FALSE',
}

export enum ISBLACK_NAVBAR_ACTION_TYPES {
  SET_ISBLACK_NAVBAR_TRUE = 'toggles/SET_ISBLACK_NAVBAR_TRUE',
  SET_ISBLACK_NAVBAR_FALSE = 'toggles/SET_ISBLACK_NAVBAR_FALSE',
}
