export enum SIGNIN_POPUP_ACTION_TYPES {
  SET_SIGNIN_POPUP_OPEN = 'toggles/SET_SIGNIN_POPUP_OPEN',
  SET_SIGNIN_POPUP_CLOSED = 'toggles/SET_SIGNIN_POPUP_CLOSED',
}

export enum SIGNUP_POPUP_ACTION_TYPES {
  SET_SIGNUP_POPUP_OPEN = 'toggles/SET_SIGNUP_POPUP_OPEN',
  SET_SIGNUP_POPUP_CLOSED = 'toggles/SET_SIGNUP_POPUP_CLOSED',
}
